import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const nodes=new Map();const node=()=>({textContent:'',value:'',hidden:false,disabled:false,setAttribute(){},removeAttribute(){},addEventListener(){},querySelectorAll(){return [];},parentElement:{parentElement:{}},focus(){},scrollIntoView(){},showModal(){},close(){}});
const document={documentElement:node(),addEventListener(){},getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},querySelector(){return node();},querySelectorAll(){return [];}};
let saved;
const sandbox={document,localStorage:{getItem(){return null;},setItem(k,v){saved=v;}},window:{addEventListener(){}},setTimeout,Date,crypto:{randomUUID:()=>String(Math.random())},console};
const script=fs.readFileSync('dist/index.html','utf8').split('<script>')[1].split('</script>')[0];
vm.createContext(sandbox);vm.runInContext(script,sandbox);
function run(code){return vm.runInContext(code,sandbox);}
assert.equal(run('createList("Viaje",["1","2"]).words.length'),2);
assert.equal(JSON.parse(saved).lists.length,2);
assert.equal(run('addWords(state.active,["2","3"]).count'),3);
const snapshot=run('JSON.stringify(state)');
assert.throws(()=>run('addWords(state.active,["1","999"])'));
assert.equal(run('JSON.stringify(state)'),snapshot);
assert.throws(()=>run('validateState({version:1,lists:[{id:"x",name:"x",words:["999"],results:[]}]})'));
assert.throws(()=>run('validateState({version:1,lists:[{id:"x",name:"x",words:["1"],results:[{score:2,total:1,date:"2026-10-01"}]}]})'));
assert.equal(run('validateState(JSON.parse(JSON.stringify(state))).lists[1].words.length'),3);
assert.equal(run('validateState({version:1,active:"principal",lists:[{id:"principal",name:"Todas",words:words.map(w=>String(w.number)),results:[{score:500,total:500,date:"2026-10-01"}]}],reviews:{}}).lists[0].words.length'),500);
const csv=run('csvFor([words[0],words[1]])');
assert.equal(csv.split('\r\n').length,2);assert.equal((csv.match(/<hr>/g)||[]).length,8);
assert.ok(csv.includes('dir=""rtl""'));
run('startExam([words[0]]);session.score=1;advance()');
assert.equal(run('activeList().results.at(-1).score'),1);
assert.equal(run('session.done'),true);
// Backward-compatible migration and honest review scheduling.
assert.equal(run('Object.keys(validateState({version:1,active:"old",lists:[{id:"old",name:"Anterior",words:["1"],results:[]}]}).reviews).length'),0);
run('state.reviews={}');
const fixed=Date.parse('2026-10-01T09:00:00Z');
for(const days of [1,3,7,14,30,30]){
  assert.equal(run(`rateWord("1","known",${fixed})`),days);
  assert.equal(run('Date.parse(state.reviews["1"].due)'),fixed+days*86400000);
}
assert.equal(run(`rateWord("1","hard",${fixed})`),1);
assert.equal(run('state.reviews["1"].level'),2);
assert.equal(run(`rateWord("1","again",${fixed})`),1);
assert.equal(run('state.reviews["1"].level'),0);
const beforeImport=run('JSON.stringify(state)');
assert.throws(()=>run('importBackup({version:1,lists:[{id:"bad",name:"Bad",words:["1"],results:[]}],reviews:{"999":{level:1,due:"2026-10-01",last:"2026-10-01"}}})'));
assert.equal(run('JSON.stringify(state)'),beforeImport);
run('importBackup({version:1,lists:[{id:"old",name:"Anterior",words:["1"],results:[]}],reviews:{"1":{level:3,due:"2026-10-10",last:"2026-10-02"}}})');
assert.equal(run('state.reviews["1"].level'),3);
assert.equal(run('state.lists.at(-1).name'),'Anterior (copia)');
const fullBackup=JSON.stringify({version:1,active:'restored',lists:[{id:'restored',name:'Viajes',words:['1','301'],results:[{score:2,total:2,date:'2026-10-01'}]}],reviews:{'301':{level:2,due:'2026-10-10',last:'2026-10-02'}}});
run('replaceBackup('+fullBackup+')');
assert.equal(run('state.lists.length'),1);
assert.equal(run('state.active'),'restored');
assert.equal(run('state.lists[0].results[0].score'),2);
assert.equal(run('state.reviews["301"].level'),2);
const restored=run('JSON.stringify(state)');
sandbox.localStorage.setItem=()=>{throw Error('Storage unavailable');};
assert.throws(()=>run('replaceBackup('+fullBackup+')'));
assert.equal(run('JSON.stringify(state)'),restored);
console.log('Verified: 500-word backups, exact restoration, atomic storage failure, merge import, review scheduling, CSV examples and exam results.');
